appprotct image os changed to debian

diff --git a/build/DockerfileForAppProtect b/build/DockerfileForAppProtect
--- a/build/DockerfileForAppProtect
+++ b/build/DockerfileForAppProtect
@@ -1,23 +1,57 @@
-FROM centos:7.4.1708
+FROM debian:stretch-slim
 
-ARG RELEASE
-COPY nginx-repo.crt nginx-repo.key /etc/ssl/nginx/
-RUN curl -o /etc/yum.repos.d/nginx-plus-7.repo https://cs.nginx.com/static/files/nginx-plus-7.repo
-#RUN echo "[app-protect-signatures]" >> /etc/yum.repos.d/signatures-7.repo \
-#&&  echo "name=app-protect-signatures" >> /etc/yum.repos.d/signatures-7.repo \
-#&& echo 'baseurl=https://app-protect-sigs.nginx.com/centos/7/$basearch/' >> /etc/yum.repos.d/signatures-7.repo
-RUN rpm --import http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6
-RUN yum install -y ca-certificates epel-release
-RUN yum install -y app-protect \
- # app-protect-attack-signatures \
-  && yum clean all \
-  && rm -rf /var/cache/yum \
-  && rm -rf /etc/ssl/nginx
+LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"
 
-RUN rm -rf /etc/nginx/nginx.conf
+ENV NGINX_PLUS_VERSION 20-1~stretch
+ARG IC_VERSION
+
+# Download certificate and key from the customer portal (https://cs.nginx.com)
+# and copy to the build context
+COPY nginx-repo.crt /etc/ssl/nginx/
+COPY nginx-repo.key /etc/ssl/nginx/
+
+# Make sure the certificate and key have correct permissions
+RUN chmod 644 /etc/ssl/nginx/*
+
+# Install NGINX Plus
+RUN set -x \
+  && apt-get update \
+  && apt-get install --no-install-recommends --no-install-suggests -y apt-transport-https ca-certificates gnupg1 libcap2-bin \
+  && \
+  NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+  found=''; \
+  for server in \
+    ha.pool.sks-keyservers.net \
+    hkp://keyserver.ubuntu.com:80 \
+    hkp://p80.pool.sks-keyservers.net:80 \
+    pgp.mit.edu \
+  ; do \
+    echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+    apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+  done; \
+  test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+  echo "Acquire::https::plus-pkgs.nginx.com::Verify-Peer \"true\";" >> /etc/apt/apt.conf.d/90nginx \
+  && echo "Acquire::https::plus-pkgs.nginx.com::Verify-Host \"true\";" >> /etc/apt/apt.conf.d/90nginx \
+  && echo "Acquire::https::plus-pkgs.nginx.com::SslCert     \"/etc/ssl/nginx/nginx-repo.crt\";" >> /etc/apt/apt.conf.d/90nginx \
+  && echo "Acquire::https::plus-pkgs.nginx.com::SslKey      \"/etc/ssl/nginx/nginx-repo.key\";" >> /etc/apt/apt.conf.d/90nginx \
+  && echo "Acquire::https::plus-pkgs.nginx.com::User-Agent  \"k8s-ic-$IC_VERSION-apt\";" >> /etc/apt/apt.conf.d/90nginx \
+  && printf "deb https://plus-pkgs.nginx.com/debian stretch nginx-plus\n" > /etc/apt/sources.list.d/nginx-plus.list \
+  && apt-get update && apt-get install -y app-protect \
+  && setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx \
+  && setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx-debug \
+  && apt-get remove --purge --auto-remove -y gnupg1 \
+  && rm -rf /var/lib/apt/lists/* \
+  && rm -rf /etc/ssl/nginx \
+  && rm /etc/apt/apt.conf.d/90nginx /etc/apt/sources.list.d/nginx-plus.list
 
 RUN usermod -u 101 nginx \
   && groupmod -g 101 nginx
+
+# forward nginx access and error logs to stdout and stderr of the ingress
+# controller process
+RUN ln -sf /proc/1/fd/1 /var/log/nginx/access.log \
+  && ln -sf /proc/1/fd/1 /var/log/nginx/stream-access.log \
+  && ln -sf /proc/1/fd/2 /var/log/nginx/error.log
 
 RUN  mkdir -p /var/lib/nginx \
   && mkdir -p /etc/nginx/secrets \
@@ -37,7 +71,7 @@ RUN  mkdir -p /var/lib/nginx \
   && chown -R nginx:nginx /var/log/f5waf/ \
   && chown -R nginx:nginx /opt/f5waf/ \
   && chown -R nginx:nginx /var/log/nginx/ \
-  && chown nginx:nginx /usr/lib64/libf5util.so \
+  #&& chown nginx:nginx /usr/lib64/libf5util.so \
   #&& chown nginx:nginx /usr/lib64/libgeoip.so \
   #&& chown nginx:nginx /usr/lib64/libgeoip1.so \
   && rm /etc/nginx/conf.d/*
@@ -45,18 +79,14 @@ RUN  mkdir -p /var/lib/nginx \
 COPY log-default.json /etc/nginx
 RUN chown nginx:nginx /etc/nginx/log-default.json
 
+EXPOSE 80 443
 
-COPY nginx-ingress /
-COPY internal/configs/version1/nginx-plus.ingress.tmpl /
-COPY internal/configs/version1/nginx-plus.tmpl /
-COPY internal/configs/version2/nginx-plus.virtualserver.tmpl  /
+COPY nginx-ingress internal/configs/version1/nginx-plus.ingress.tmpl internal/configs/version1/nginx-plus.tmpl internal/configs/version2/nginx-plus.virtualserver.tmpl  /
 
 # Uncomment the line below if you would like to add the default.pem to the image
 # and use it as a certificate and key for the default server
 # ADD default.pem /etc/nginx/secrets/default
 
-ADD protect_start.sh /
-RUN chmod +x /protect_start.sh
-RUN setcap cap_net_bind_service=+ep /usr/sbin/nginx 
+USER nginx
 
 ENTRYPOINT ["/nginx-ingress"]
